### ISSUE TITLE
Error: Fuel cannot be imported via CSV

### ISSUE THREAD

**Issue by mmartinortiz** [hargata/lubelog#189]
LubeLogger `1.0.9`

Steps to reproduce:
- Start LubeLogger using docker compose
- Create a new car
- Download `gassample.csv`
- Import `gassample.csv`

Error:

```
app_1  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
app_1  |       No XML encryptor configured. Key {24c0b5a6-2979-46f8-b7a9-9779ff30a2bc} may be persisted to storage in unencrypted form.
app_1  | fail: CarCareTracker.Controllers.VehicleController[0]
app_1  |       Error Occurred While Bulk Inserting
app_1  |       System.FormatException: String '' was not recognized as a valid DateTime.
app_1  |          at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
app_1  |          at System.DateTime.Parse(String s)
app_1  |          at CarCareTracker.Controllers.VehicleController.ImportToVehicleIdFromCsv(Int32 vehicleId, ImportMode mode, String fileName) in /App/Controllers/VehicleController.cs:line 375
```

**Comment by hargata** [comment]
I cannot reproduce this error. I believe it's a locale error.
The CSV sample export is a hardcoded file that only exports Dates in North American "MM/dd/yyyy". It serves only as a sample as to what the column names should be and the data type in each column: Dates, numeric, string, decimals, etc.

You should try to create some fuel entries, export them as CSV and then reimport them, they should work fine.

**Comment by mmartinortiz** [comment]
Thanks for the quick reply.

Indeed, I changed the locales. That must be the cause. I have followed your example and add some records manually for exporting them later, but the "export" button is gone after I added the first entry.

![image](https://github.com/hargata/lubelog/assets/4763770/0cf5a694-4a04-4c26-b41b-6c3ae097571e)

**Comment by hargata** [comment]
@mmartinortiz I think you might have a config persisting issue. If you're running this in docker, make sure the config volume is mounted. If you're running the windows standalone executable, make sure you have a /config folder.

The Import/Export functionality is in the Settings tab:

![image](https://github.com/hargata/lubelog/assets/155338622/71c772a4-4bcc-404c-9c5c-e8c0eb79308d)

Enable this and the export functionality should show up.
