### ISSUE TITLE
Unable to Connect to Lubelogger

### ISSUE THREAD

**Issue by Bovive** [hargata/lubelog#196]
I am unsure which update this started to occur, but I am unable to access Lubelogger. I did not see any previous versions listed for Docker, so I am only able to test this with the latest version. When I attempt to access the site I receive the browser error of "ERR_TOO_MANY_REDIRECTS".

The logs show:

`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
         at System.IO.FileSystemWatcher.StartRaisingEvents()
         at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
         at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
         at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
         at Microsoft.AspNetCore.Mvc.Razor.Infrastructure.DefaultFileVersionProvider.AddFileVersionToPath(PathString requestPathBase, String path)
         at Microsoft.AspNetCore.Mvc.TagHelpers.LinkTagHelper.Process(TagHelperContext context, TagHelperOutput output)
         at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
         at AspNetCoreGeneratedDocument.Views_Shared__Layout.<>c__DisplayClass34_0.<<ExecuteAsync>b__0>d.MoveNext() in /App/Views/Shared/_Layout.cshtml:line 32
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
         at AspNetCoreGeneratedDocument.Views_Shared__Layout.ExecuteAsync() in /App/Views/Shared/_Layout.cshtml:line 21
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
         at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
info: CarCareTracker.Middleware.Authen[7]
      AuthN was not authenticated. Failure message: Cookie is invalid or does not exist.
info: CarCareTracker.Middleware.Authen[12]
      AuthenticationScheme: AuthN was challenged.`

**Comment by hargata** [comment]
Can you try clearing your cookies?

**Comment by Bovive** [comment]
Unfortunately clearing the cookies did not help. Uptime Kuma also receives the same error.

**Comment by hargata** [comment]
@Bovive can you check your docker compose to make sure you have the keys volume mounted?

**Comment by hargata** [comment]
If that didn't work, can you navigate into your config volume and look for userConfig.json, and then look for the EnableAuth key and set that to false? Trying to narrow down whether this is an auth bug or something else.

**Comment by hargata** [comment]
I believe I might have found the issue, just released a fix for it, can you pull down the latest docker image and test?

**Comment by Bovive** [comment]
> I believe I might have found the issue, just released a fix for it, can you pull down the latest docker image and test?

Yup, that fixed it. Thanks!

**Comment by ilgigante77** [comment]
Ok sorry, I found out why. I don't know if it was already sayd in other places, but there is a limit on the open files. I raised it to more than 8k like said here: https://github.com/moby/moby/issues/1044
