### ISSUE TITLE
Unable to log in after container update

### ISSUE THREAD

**Issue by ionyx0** [hargata/lubelog#21]
Running using docker-compose with authentication enabled, if the container rebuilds, the data protection key being used cannot be found.  Please see the logs from my container below.

Repro:
- Configure docker-compose.yml as needed and start up the container.
- Enable authentication and set a username/password
- Stop and delete the container
- Start again using docker-compose.yml
- The page on load will be blank with a thrown error in the log file

Log file:
```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]

      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed. For more information go to https://aka.ms/aspnet/dataprotectionwarning

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]

      No XML encryptor configured. Key {d318d71b-38fb-4cb4-9d42-fcce247d73f0} may be persisted to storage in unencrypted form.

info: Microsoft.Hosting.Lifetime[14]

      Now listening on: http://[::]:8080

info: Microsoft.Hosting.Lifetime[0]

      Application started. Press Ctrl+C to shut down.

info: Microsoft.Hosting.Lifetime[0]

      Hosting environment: Production

info: Microsoft.Hosting.Lifetime[0]

      Content root path: /App

fail: Microsoft.AspNetCore.Server.Kestrel[13]

      Connection id "0HN0FPCTRMNIL", Request id "0HN0FPCTRMNIL:00000001": An unhandled exception was thrown by the application.

      System.Security.Cryptography.CryptographicException: The key {d868915a-a32c-432a-9d92-0c2e04cc3e06} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning

         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)

         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)

         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)

         at CarCareTracker.Middleware.Authen.HandleAuthenticateAsync() in /App/Middleware/Authen.cs:line 55

         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()

         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)

         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by hargata** [comment]
Ah! I had a feeling this was going to happen with Dockerization, In the meantime, the only workaround I can think off is editing the userConfig.json file and set enableAuth to false.
I will work on adding the volume so that keys may persist in containers.

**Comment by hargata** [comment]
@ionyx0 this is now fixed, you probably still have to reset the userConfig.json file to disable auth but the keys should now persist.

**Comment by florianschroen** [comment]
We need an addition volume in the docker compose files to keep the keystore /root/.aspnet/DataProtection-Keys


```
services:
  app:
    volumes:
      - aspnetdata:/root/.aspnet
... 

volumes:
  aspnetdata:
... 



```

**Comment by hargata** [comment]
@florianschroen I just added that

**Comment by ionyx0** [comment]
@hargata That's the solution... working here now.  Thanks!
