### ISSUE TITLE
Issue with Enabling Authentication

### ISSUE THREAD

**Issue by jackthomasanderson** [hargata/lubelog#286]
Hello,

First of all, a big thank you for this superb application!

I've just deployed a container with the following configuration:

```bash
docker volume create lubelogger_config
docker volume create lubelogger_data
docker volume create lubelogger_translations
docker volume create lubelogger_documents
docker volume create lubelogger_images
docker volume create lubelogger_temp
docker volume create lubelogger_log
docker volume create lubelogger_keys

docker run -d \
  --name lubelogger \
  -v lubelogger_config:/App/config \
  -v lubelogger_data:/App/data \
  -v lubelogger_translations:/App/wwwroot/translations \
  -v lubelogger_documents:/App/wwwroot/documents \
  -v lubelogger_images:/App/wwwroot/images \
  -v lubelogger_temp:/App/wwwroot/temp \
  -v lubelogger_log:/App/log \
  -v lubelogger_keys:/root/.aspnet/DataProtection-Keys \
  -p 80:8080 \
  -e LC_ALL=en_US.UTF-8 \
  -e LANG=en_US.UTF-8 \
  -e MailConfig__EmailServer=smtp.gmail.com \
  -e MailConfig__EmailFrom=myuser@gmail.com \
  -e MailConfig__UseSSL=true \
  -e MailConfig__Port=587 \
  -e MailConfig__Username=myuser@gmail.com \
  -e MailConfig__Password=mysecretpass \
  -e LOGGING__LOGLEVEL__DEFAULT=Error \
  ghcr.io/hargata/lubelogger:latest
```

When I enable the "Enable Authentication" feature and enter a username with its password, I get an error "An error has occurred, please try again later".

Any idea what could be causing this issue?

Some logs :

```bash
2024-02-14T08:18:46.970127925Z fail: CarCareTracker.Controllers.LoginController[0]
2024-02-14T08:18:46.970233980Z       Error on saving config file.
2024-02-14T08:18:46.970242740Z       System.IO.FileNotFoundException: Could not find file '/App/config/userConfig.json'.
2024-02-14T08:18:46.970251936Z       File name: '/App/config/userConfig.json'
2024-02-14T08:18:46.970260798Z          at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2024-02-14T08:18:46.970267669Z          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024-02-14T08:18:46.970275159Z          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2024-02-14T08:18:46.970283602Z          at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
2024-02-14T08:18:46.970290131Z          at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
2024-02-14T08:18:46.970296279Z          at System.IO.File.ReadAllText(String path, Encoding encoding)
2024-02-14T08:18:46.970304489Z          at CarCareTracker.Logic.LoginLogic.CreateRootUserCredentials(LoginModel credentials) in /App/Logic/LoginLogic.cs:line 283
2024-02-14T08:18:46.970313594Z          at CarCareTracker.Controllers.LoginController.CreateLoginCreds(LoginModel credentials) in /App/Controllers/LoginController.cs:line 101
```

If I understand correctly, these logs indicate an error during the configuration file saving process. A FileNotFoundException exception is thrown because the file /App/config/userConfig.json was not found. This error seems to occur when attempting to access the file for reading, resulting in an error during the execution of the CreateRootUserCredentials method in LoginLogic.

**Comment by hargata** [comment]
This bug will be fixed and a release will be created tonight.

For now, a workaround will be to toggle Darkmode on/off and then enable authentication.

**Comment by hargata** [comment]
Fix is released, closing ticket.

**Comment by jackthomasanderson** [comment]
> This bug will be fixed and a release will be created tonight.
> 
> For now, a workaround will be to toggle Darkmode on/off and then enable authentication.

Haha, that workaround is indeed quite amusing! It's like being asked to turn off the lights in the room to solve the issue. Thanks again for your prompt response!
