### ISSUE TITLE
SMTP server issue with Fastmail

### ISSUE THREAD

**Issue by janteau** [hargata/lubelog#582]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Troubleshooting)
- [x] I have searched through existing issues.

**Description**

Mail sending doesn't appear to work with Fastmail's SMTP server.  I have tried both port 465 (SSL) and 587 (STARTTLS).  https://www.fastmail.help/hc/en-us/articles/1500000278342-Server-names-and-ports

**Platform**
- [x] Docker Image
- [ ] Windows Standalone Executable

**Browser Console Errors(F12)**

**App/Container Console Error**

```
Recreating lubelogger_app_1 ... done
Attaching to lubelogger_app_1
app_1  | LubeLogger 1.3.5
app_1  | Website: https://lubelogger.com
app_1  | Documentation: https://docs.lubelogger.com
app_1  | GitHub: https://github.com/hargata/lubelog
app_1  | SMTP Configured for "smtp.fastmail.com"
app_1  | Message Of The Day: Not Configured
app_1  | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
app_1  |       An unhandled exception has occurred while executing the request.
app_1  |       System.UriFormatException: Invalid URI: The hostname could not be parsed.
app_1  |          at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
app_1  |          at System.Uri..ctor(String uriString)
app_1  |          at MailKit.Net.Smtp.SmtpClient.ComputeDefaultValues(String host, Int32& port, SecureSocketOptions& options, Uri& uri, Boolean& starttls)
app_1  |          at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
app_1  |          at CarCareTracker.Helper.MailHelper.SendEmail(List`1 emailTo, String emailSubject, String emailBody) in /App/Helper/MailHelper.cs:line 148
app_1  |          at CarCareTracker.Helper.MailHelper.NotifyUserForRegistration(String emailAddress, String token) in /App/Helper/MailHelper.cs:line 40
app_1  |          at CarCareTracker.Logic.LoginLogic.GenerateUserToken(String emailAddress, Boolean autoNotify) in /App/Logic/LoginLogic.cs:line 322
app_1  |          at lambda_method38(Closure, Object, Object[])
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
app_1  |       --- End of stack trace from previous location ---
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
app_1  |       --- End of stack trace from previous location ---
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
app_1  |       --- End of stack trace from previous location ---
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
app_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
app_1  |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
app_1  |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Screenshots(optional)**

**Comment by hargata** [comment]
try removing the quotes around `smtp.fastmail.com`

**Comment by janteau** [comment]
That fixed it!  I removed all the quotes from the mail settings in the .env file and it's working now.  

Thanks!
