### ISSUE TITLE
Unable to access from another device - on Windows

### ISSUE THREAD

**Issue by r0gueone** [hargata/lubelog#718]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x ] I have searched through existing issues.

**Description**
I have deployed LubeLogger into my Windows Server environment.  It runs fine locally.  But when attempting to access from another device's browser, it times out.  I reviewed the documentation and attempted to add the required Kestrel block, but when I do that, the application crashes and won't run locally.

**Platform**
- [ ] Docker Image
- [x ] Windows Standalone Executable

If I add the following:  (IP obscured for security)

"Kestrel": {
   "Endpoints": {
     "Http": {
       "Url": "http://192.168.x.x:5000"
     },
     "Https": {
       "Url": "https://192.168.x.x:5011"
     },
}

I then get the following error when trying to run LubeLogger:

Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file 'C:\Tools\LubeLogger\appsettings.json'.
 ---> System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: '"' is invalid after a single JSON value. Expected end of data. LineNumber: 36 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ApplyDefaultAppConfiguration(HostBuilderContext hostingContext, IConfigurationBuilder appConfigBuilder, String[] args)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)

I have tried to add this block at the beginning and end of the "appsettings.json" but still same error.  It always indicates the Line Number of where I've added it.  But it will never start up once I add this section.

**Comment by hargata** [comment]
You're missing a comma in your appsettings.json

**Comment by r0gueone** [comment]
I wish it were that simple.  Still doesn't work.  Does this block go at the end of the JSON file?  I've tried adding it after this block:

  "VisibleTabs": [ 0, 1, 4, 2, 3, 6, 5, 8 ],
  "TabOrder": [ 8, 9, 10, 0, 1, 4, 2, 7, 3, 6, 5 ],
  "DefaultTab": 8,
  "UserNameHash": "",
  "UserPasswordHash": "",
  "DefaultReminderEmail": ""
}

And also before the closing } of that block, still doesn't work.

Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file 'C:\Tools\LubeLogger\appsettings.json'.
 ---> System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: ',' is invalid after a single JSON value. Expected end of data. LineNumber: 36 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)

**Comment by hargata** [comment]
Just paste your appsettings.json in here without the sensitive information

**Comment by r0gueone** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "UseDarkMode": false,
  "UseSystemColorMode": false,
  "EnableCsvImports": true,
  "UseMPG": true,
  "UseDescending": false,
  "EnableAuth": false,
  "DisableRegistration": false,
  "EnableRootUserOIDC": false,
  "HideZero": false,
  "EnableAutoReminderRefresh": false,
  "EnableAutoOdometerInsert": false,
  "EnableShopSupplies": false,
  "EnableExtraFieldColumns": false,
  "UseUKMPG": false,
  "UseThreeDecimalGasCost": true,
  "UseMarkDownOnSavedNotes": false,
  "HideSoldVehicles": false,
  "PreferredGasMileageUnit": "",
  "UserColumnPreferences": [],
  "PreferredGasUnit": "",
  "UserLanguage": "en_US",
  "VisibleTabs": [ 0, 1, 4, 2, 3, 6, 5, 8 ],
  "TabOrder": [ 8, 9, 10, 0, 1, 4, 2, 7, 3, 6, 5 ],
  "DefaultTab": 8,
  "UserNameHash": "",
  "UserPasswordHash": "",
  "DefaultReminderEmail": ""
}
,"Kestrel": {
   "Endpoints": {
     "Http": {
       "Url": "http://192.168.x.x:5000"
     },
     "Https": {
       "Url": "https://192.168.x.x:5011"
     },
}

**Comment by hargata** [comment]
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "UseDarkMode": false,
  "UseSystemColorMode": false,
  "EnableCsvImports": true,
  "UseMPG": true,
  "UseDescending": false,
  "EnableAuth": false,
  "DisableRegistration": false,
  "EnableRootUserOIDC": false,
  "HideZero": false,
  "EnableAutoReminderRefresh": false,
  "EnableAutoOdometerInsert": false,
  "EnableShopSupplies": false,
  "EnableExtraFieldColumns": false,
  "UseUKMPG": false,
  "UseThreeDecimalGasCost": true,
  "UseMarkDownOnSavedNotes": false,
  "HideSoldVehicles": false,
  "PreferredGasMileageUnit": "",
  "UserColumnPreferences": [],
  "PreferredGasUnit": "",
  "UserLanguage": "en_US",
  "VisibleTabs": [
    0,
    1,
    4,
    2,
    3,
    6,
    5,
    8
  ],
  "TabOrder": [
    8,
    9,
    10,
    0,
    1,
    4,
    2,
    7,
    3,
    6,
    5
  ],
  "DefaultTab": 8,
  "UserNameHash": "",
  "UserPasswordHash": "",
  "DefaultReminderEmail": "",
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://192.168.x.x:5000"
      },
      "Https": {
        "Url": "https://192.168.x.x:5011"
      }
    }
  }
}
```

**Comment by r0gueone** [comment]
Thank you!  That worked.  Very much appreciated.
