### ISSUE TITLE
[bug]: ERR_TOO_MANY_REDIRECTS. Console:  Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]

### ISSUE THREAD

**Issue by zd3sf** [hargata/lubelog#738]
**Checklist**
Please make sure you have performed the following steps before opening a new bug ticket, change `[ ]` to `[x]` to mark it as done

- [x ] I have read and tried the steps outlined in the [Troubleshooting Guide](https://docs.lubelogger.com/Installation/Troubleshooting)
- [x ] I have searched through existing issues.

**Description**
After updating to 1.4 from 1.3.8, can't reach to lubelogger. even on incognito. 

**Platform**
- [ ] Docker Image
- [x ] Windows Standalone Executable

**Browser Console Errors(F12)**
![image](https://github.com/user-attachments/assets/ddeb6b09-8848-404c-bac4-ca0767b3028e)

**App/Container Console Error**
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at System.ArgumentNullException.Throw(String paramName)
         at System.Boolean.Parse(String value)
         at CarCareTracker.Helper.ConfigHelper.GetUserConfig(ClaimsPrincipal user) in C:\Users\DESK-555BD\Downloads\lubelog-1.4.0\lubelog-1.4.0\Helper\ConfigHelper.cs:line 184
         at AspNetCoreGeneratedDocument.Views_Shared__Layout.ExecuteAsync() in C:\Users\DESK-555BD\Downloads\lubelog-1.4.0\lubelog-1.4.0\Views\Shared\_Layout.cshtml:line 7
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
         at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**config**
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "UseDarkMode": false,
  "UseSystemColorMode": false,
  "EnableCsvImports": true,
  "UseMPG": true,
  "UseDescending": false,
  "EnableAuth": false,
  "DisableRegistration": false,
  "EnableRootUserOIDC": false,
  "HideZero": false,
  "EnableAutoReminderRefresh": false,
  "EnableAutoOdometerInsert": false,
  "EnableShopSupplies": false,
  "EnableExtraFieldColumns": false,
  "UseUKMPG": false,
  "UseThreeDecimalGasCost": true,
  "UseMarkDownOnSavedNotes": false,
  "HideSoldVehicles": false,
  "PreferredGasMileageUnit": "",
  "UserColumnPreferences": [],
  "PreferredGasUnit": "",
  "UserLanguage": "en_US",
  "VisibleTabs": [ 0, 1, 4, 2, 3, 6, 5, 8 ],
  "DefaultTab": 8,
  "UserNameHash": "",
  "UserPasswordHash": "",
  "DefaultReminderEmail":  "",
  "Kestrel": {"Endpoints": {"Http": {"Url": "http://192.168.1.167:5000"},},},
  "MailConfig": {
    "EmailServer": "smtp.gmail.com",
    "EmailFrom": "LubeLogger",
    "UseSSL": true,
    "Port": 587,
    "Username": "**********",
    "Password": "************"}
}
```

**Comment by zd3sf** [comment]
Downgrading to 1.3.9 makes it work again.

**Comment by hargata** [comment]
your appsettings.json is outdated.
