### ISSUE TITLE
[Feature Request] GUI translation to different language

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog#76]
I would love to have GUI in Slovenian language. And I am sure other non English users as well in theirs. So having an option to change the languege would be very much appreciated.

Maybe using crowdin to store and collect the translated strings?

**Comment by ricowalker** [comment]
+1 here, could contribute to Dutch here.

**Comment by joschygit** [comment]
Hi, i could contribute to German.

**Comment by devzwf** [comment]
Hi i could help to french

**Comment by jader31** [comment]
I'm here to help with Brazilian Portuguese.

**Comment by devzwf** [comment]
where are we with this ?

**Comment by hargata** [comment]
@devzwf currently working on the key value file, so far I have the keys for the tab names and the settings.

**Comment by devzwf** [comment]
any help needed ? aside of the actual translation....

**Comment by hargata** [comment]
@devzwf it just hasn't been prioritized since there's other features and enhancements that takes priority.

**Comment by devzwf** [comment]
no worry, i totally understand :)

**Comment by hargata** [comment]
well, I've added the ability to translate about ~95% of the UI, please read this doc regarding how to create your own translation file:
https://docs.lubelogger.com/Translations

**Comment by devzwf** [comment]
the format of en_US.json is horrible 
is it me only ? 1 liner ?

**Comment by thehijacker** [comment]
Great job. But not sure if it is working...

I took the file en_US.json from https://github.com/hargata/lubelog/blob/main/wwwroot/defaults/en_US.json.

Translated everything to Slovenian and renamed it to sl_SI.json. Next I uploaded it and selected the new sl_SI as language. Then the worls went dark :D.

I get in GUI:

![image](https://github.com/hargata/lubelog/assets/13857043/ecda3186-0496-4172-ad1f-50d3da96d86c)

And this is the log:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Text.Json.JsonException: '"' is invalid after a property name. Expected a ':'. Path: $.Export_to_CSV | LineNumber: 107 | BytePositionInLine: 141.
       ---> System.Text.Json.JsonReaderException: '"' is invalid after a property name. Expected a ':'. LineNumber: 107 | BytePositionInLine: 141.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
         at System.Text.Json.Utf8JsonReader.ConsumePropertyName()
         at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
         at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         --- End of inner exception stack trace ---
         at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at CarCareTracker.Helper.TranslationHelper.<>c__DisplayClass4_0.<Translate>b__0(ICacheEntry entry) in /App/Helper/TranslationHelper.cs:line 34
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
         at CarCareTracker.Helper.TranslationHelper.Translate(String userLanguage, String text) in /App/Helper/TranslationHelper.cs:line 28
         at AspNetCoreGeneratedDocument.Views_Home_Index.ExecuteAsync() in /App/Views/Home/Index.cshtml:line 20
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
         at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

Not sure that your en_US.json is a valid JSON file. Well any tip on how to get GUI back and how to fix my translation file would be much appreciated.

**Comment by hargata** [comment]
@devzwf the file is minified which means all line breaks are removed, you need to use a json pretty print to format it in human readable form.

@thehijacker let me try your translation file real quick, but if you delete the translation file and restart your docker container it should revert back to en-US

**Comment by thehijacker** [comment]
Could not find my sl_SI.json file. So I edited file userConfig.json and change from sl_SI to en_US and restarted container. GUI now works.

**Comment by hargata** [comment]
@thehijacker you're right, I'll be updating those keys real quick.

**Comment by hargata** [comment]
@thehijacker actually I found the error in your translation file, on line 108 you have the key copied twice.
here I fixed it.
[sl_SI.json](https://github.com/hargata/lubelog/files/14158075/sl_SI.json)

**Comment by thehijacker** [comment]
Ah yes. I was trying to figure that key and must have copy pasted it twice. Still it is not a valid json. But it works now. Will go over translation in GUI and see if there is something I can improve. This for sure is not final translation. Can I post it here for you to add in the code tree once it is done?

**Comment by hargata** [comment]
@thehijacker I made a separate repo for translations so people can choose which translation files to download:
When you've finalized the translation you can add a pull request on there to have it merged in to that repo.
https://github.com/hargata/lubelog_translations

**Comment by thehijacker** [comment]
Done. Improved the translation. Double checked everything and made a pull request. But not sure there will be three Slovenian users to confirm it. My wife is good enough for three others to confirm if all is correct :).

**Comment by hargata** [comment]
@thehijacker I merged your translation into the repo, we should be able close this since the feature for adding / loading translations is delivered?
